server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: provider-api
          uri: http://provider-api:8080          # ðŸ‘ˆ ESTE ES EL BUENO
          predicates:
            - Path=/api/Provider/**             # ðŸ‘ˆ ENDPOINTS DEL PROVIDER API
        - id: provider-health
          uri: http://provider-api:8080
          predicates:
            - Path=/health

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
