server:
  port: 8080

spring:
  data:
    mongodb:
      uri: "mongodb://mongo:ibUfMftVvUUsTtDoOkclCIJfmgrvyWnZ@mainline.proxy.rlwy.net:33104/ordenes?authSource=admin"

catalogo:
  service:
    url: http://catalogo-servicio:8080