version: '3.8'

services:
  usuarios-db:
    image: mysql:8.0
    container_name: usuarios-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: usuarios_user
      MYSQL_PASSWORD: usuarios_pass
    ports:
      - "3306:3306"
    volumes:
      - usuarios-db-data:/var/lib/mysql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - microservices-network

  create-topics:
    image: apache/kafka:latest
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Waiting for Kafka to start...';
      sleep 5;
      kafka-topics.sh --bootstrap-server kafka:9092 --create --topic notifications-payment --partitions 3 --replication-factor 1;
      kafka-topics.sh --bootstrap-server kafka:9092 --create --topic notification-envios --partitions 3 --replication-factor 1;
      kafka-topics.sh --bootstrap-server kafka:9092 --create --topic topic3 --partitions 3 --replication-factor 1;
      echo 'Topics created successfully.';
      "
    networks:
      - microservices-network

  usuarios-service:
    build:
      context: ./Usuarios
      dockerfile: Dockerfile
    container_name: usuarios-service
    ports:
      - "8085:8080"   # Puerto de la aplicaci칩n
      - "9990:9990"   # Puerto de administraci칩n (opcional)
    environment:
      # Configuraci칩n de base de datos
      - DB_HOST=usuarios-db
      - DB_PORT=3306
      - DB_NAME=usuarios_db
      - DB_USER=usuarios_user
      - DB_PASSWORD=usuarios_pass
      # Ruta donde estar치 montado el archivo Firebase
      - FIREBASE_CREDENTIALS_PATH=/opt/jboss/wildfly/firebase-credentials.json
    volumes:
      - ./Usuarios/firebase-credentials.json:/opt/jboss/wildfly/firebase-credentials.json:ro
      
      - ./logs:/opt/jboss/wildfly/standalone/log
    depends_on:
      usuarios-db:
        condition: service_healthy
    networks:
      - microservices-network

  catalogo-service:
    build:
      context: ./catalogo
      dockerfile: Dockerfile
    container_name: catalogo-service
    ports:
      - "8081:8080"
    depends_on:
      - usuarios-service
    networks:
      - microservices-network

  pagos-service:
    build:
      context: ./pagos
      dockerfile: Dockerfile
    container_name: pagos-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
    networks:
      - microservices-network

  proveedores-service:
    build:
      context: ./proveedores
      dockerfile: Dockerfile
    container_name: proveedores-service
    ports:
      - "8088:8080"
    depends_on:
      - catalogo-service
    networks:
      - microservices-network

  notificaciones-service:
    build:
      context: ./notificaciones
      dockerfile: Dockerfile
    container_name: notificaciones-service
    ports:
      - "8087:8000"
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka
    networks:
      - microservices-network

  envios-service:
    build:
      context: ./envios        # ruta de tu proyecto Python
      dockerfile: Dockerfile
    container_name: envios-service
    ports:
      - "8089:8000"   # FastAPI corriendo en 8000 dentro del contenedor
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - usuarios-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  usuarios-db-data: