spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proveedores_db?useSSL=false&serverTimezone=UTC
    username: root
    password: tu_contrase√±a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8088
