spring:
  datasource:
    url: jdbc:mysql://root:CgIXXmIHMGTLgzhhvkjMTezBoHlUFvyj@hopper.proxy.rlwy.net:38807/railway
    username: root
    password: CgIXXmIHMGTLgzhhvkjMTezBoHlUFvyj
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8088
